version: '3.8'
services:
  publisher:
    build: ./publisher
    ports:
      - "8080:80"
    depends_on:
      - mosquitto

  subscriber:
    build: ./subscriber
    ports:
      - "8081:80"
    depends_on:
      - mosquitto
      
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - publisher
      - subscriber
